import React from 'react';
import { motion } from 'framer-motion';
import { Brain, AlertTriangle, CheckCircle, TrendingDown, Info, Download, FileText } from 'lucide-react';
import { Card, CardHeader } from '@/components/common/Card';
import { Badge } from '@/components/common/Badge';
import { Button } from '@/components/common/Button';
import { DataTable, Column } from '@/components/tables/DataTable';
import { DonutChart, BarChartComponent } from '@/components/charts/Charts';
import { mockResults, mockAIInsights, mockScoreDistribution } from '@/services/mockData';
import { ExamResult, AIInsight, AlertSeverity } from '@/types';
import { formatDate, formatPercentage } from '@/utils';
import { useNavigate } from 'react-router-dom';
import { ROUTES } from '@/constants';

const severityBadgeMap: Record<AlertSeverity, 'danger' | 'warning' | 'success' | 'primary'> = {
  [AlertSeverity.CRITICAL]: 'danger',
  [AlertSeverity.HIGH]: 'danger',
  [AlertSeverity.MEDIUM]: 'warning',
  [AlertSeverity.LOW]: 'success',
};

const resultColumns: Column<ExamResult>[] = [
  { key: 'studentName', header: 'Student', sortable: true },
  { key: 'obtainedMarks', header: 'Score', sortable: true, render: (v, row) => `${v}/${row.totalMarks}` },
  { key: 'percentage', header: '%', sortable: true, align: 'center', render: (v) => <span className="font-mono">{String(v)}%</span> },
  { key: 'grade', header: 'Grade', align: 'center', render: (v) => {
    const g = String(v);
    return <Badge variant={g === 'O' || g === 'A+' ? 'success' : g === 'F' ? 'danger' : 'warning'}>{g}</Badge>;
  }},
  {
    key: 'aiFlags',
    header: 'AI Flags',
    align: 'center',
    render: (v) => {
      const flags = v as ExamResult['aiFlags'];
      return flags.length > 0 ? (
        <Badge variant="danger">{flags.length} flag{flags.length > 1 ? 's' : ''}</Badge>
      ) : (
        <span className="text-success-600 text-xs font-medium">Clean</span>
      );
    },
  },
];

export function AIReportPage() {
  const navigate = useNavigate();

  const passed = mockResults.filter((r) => r.percentage >= 40).length;
  const failed = mockResults.filter((r) => r.percentage < 40).length;
  const avg = mockResults.length ? mockResults.reduce((s, r) => s + r.percentage, 0) / mockResults.length : 0;

  return (
    <div className="space-y-6">
      <div className="flex items-start justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <Brain className="h-5 w-5 text-secondary" />
            <span className="text-sm font-medium text-secondary-600 dark:text-secondary-400">Explainable AI Report</span>
          </div>
          <h1 className="font-display font-bold text-foreground text-2xl">Database Management Systems</h1>
          <p className="text-muted-foreground text-sm mt-0.5">CS302-MID-2024 · Generated {formatDate(new Date().toISOString())}</p>
        </div>
        <Button variant="outline" leftIcon={<Download className="h-4 w-4" />}>
          Export PDF
        </Button>
      </div>

      {/* Summary cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {[
          { label: 'Total Appeared', value: mockResults.length, color: 'text-foreground' },
          { label: 'Passed', value: passed, color: 'text-success-600' },
          { label: 'Failed', value: failed, color: 'text-danger-600' },
          { label: 'Avg Score', value: `${avg.toFixed(1)}%`, color: 'text-foreground' },
        ].map((s, i) => (
          <motion.div
            key={s.label}
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.05 }}
            className="rounded-xl border border-border bg-card p-4 text-center shadow-soft"
          >
            <p className={`font-display font-bold text-2xl ${s.color}`}>{s.value}</p>
            <p className="text-xs text-muted-foreground mt-1">{s.label}</p>
          </motion.div>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">
        {/* AI Insights */}
        <div className="lg:col-span-2 space-y-4">
          <Card>
            <CardHeader title="AI Insights" description="Patterns and recommendations generated by AI" icon={<Brain className="h-4 w-4" />} />
            <div className="space-y-3">
              {mockAIInsights.map((insight, i) => (
                <motion.div
                  key={insight.id}
                  initial={{ opacity: 0, x: -8 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: i * 0.08 }}
                  className="p-4 rounded-lg border border-border bg-muted/30"
                >
                  <div className="flex items-start justify-between gap-2 mb-2">
                    <div className="flex items-center gap-2">
                      <Badge variant={severityBadgeMap[insight.severity]}>{insight.severity}</Badge>
                      <span className="text-xs text-muted-foreground">{insight.category}</span>
                    </div>
                    <span className="text-xs text-muted-foreground">{insight.affectedStudents} students</span>
                  </div>
                  <p className="text-sm text-foreground font-medium mb-1.5">{insight.insight}</p>
                  <div className="flex gap-2 text-xs text-muted-foreground">
                    <Info className="h-3.5 w-3.5 flex-shrink-0 mt-0.5" />
                    <span>{insight.recommendation}</span>
                  </div>
                </motion.div>
              ))}
            </div>
          </Card>

          {/* Results table */}
          <Card>
            <CardHeader title="Student Results" icon={<FileText className="h-4 w-4" />} />
            <DataTable
              data={mockResults}
              columns={resultColumns}
              keyField="id"
              searchable
              searchFields={['studentName']}
              pageSize={5}
              emptyTitle="No results"
            />
          </Card>
        </div>

        {/* Charts */}
        <div className="space-y-4">
          <Card>
            <CardHeader title="Pass / Fail" icon={<CheckCircle className="h-4 w-4" />} />
            <DonutChart
              data={[
                { name: 'Passed', value: passed },
                { name: 'Failed', value: failed },
              ]}
              centerLabel="Appeared"
              centerValue={mockResults.length}
              innerRadius={50}
              outerRadius={80}
            />
          </Card>

          <Card>
            <CardHeader title="Score Distribution" icon={<TrendingDown className="h-4 w-4" />} />
            <BarChartComponent
              data={mockScoreDistribution}
              bars={[{ key: 'value', label: 'Students' }]}
              xKey="name"
              height={180}
            />
          </Card>
        </div>
      </div>
    </div>
  );
}
